version: '3'

services:
  api:
    image: manuelcascopeebles/melichallenge:latest
    ports:
      - "80:80"
    environment:
      MIGRATION_RUN: not_execute
      ENVIRONMENT_MODE: Production
      INSTALL_XDEBUG: execute
      FIRST_UP: execute
      DB_HOST: db
      DB_DATABASE: mutant
      DB_USERNAME: root
      DB_PASSWORD: root
      API_HOST: localhost
    volumes:
      - ./api:/var/www/html/
      - logs:/var/www/logs

  migrations:
      image: manuelcascopeebles/melichallenge:latest
      environment:
        MIGRATION_RUN: execute
        ENVIRONMENT_MODE: Production
        INSTALL_XDEBUG: not_execute
        FIRST_UP: execute
        DB_HOST: db
        DB_DATABASE: mutant
        DB_USERNAME: root
        DB_PASSWORD: root
        API_HOST: localhost
      volumes:
          - ./api:/var/www/html/
          - logs:/var/www/logs


  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data_melichallenge:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mutant
    ports:
      - 6033:3306


volumes:
  db_data_melichallenge: {}
  logs:
        driver: local
