#!/bin/bash

# ENVIRONMENT VARIABLES -----------------------------------

	echo "ENVIRONMENT_MODE: $ENVIRONMENT_MODE"
	echo "API_HOST: $API_HOST"
	echo "MIGRATION_RUN: $MIGRATION_RUN"
	echo "DATABASE: $DB_DATABASE"
	echo "DB_HOST: $DB_HOST"

    cp /var/www/html/template.env.vars /var/www/html/.env

	sed -i "s/DB_HOST_PLACEHOLDER/${DB_HOST}/g" /var/www/html/.env
	sed -i "s/DB_DATABASE_PLACEHOLDER/${DB_DATABASE}/g" /var/www/html/.env
	sed -i "s/DB_USERNAME_PLACEHOLDER/${DB_USERNAME}/g" /var/www/html/.env
	sed -i "s/DB_PASSWORD_PLACEHOLDER/${DB_PASSWORD}/g" /var/www/html/.env

# FIRST-UP

	if [ "${FIRST_UP}" == 'execute' ] ; then
		echo 'Running Composer Install...'
		cd /var/www/html
		composer install
		echo 'Composer Install Done!'
	fi

# WAIT FOR MYSQL READY -----------------------------------

	echo 'Checking MySql...'
	while !(mysqladmin ping --host=$DB_HOST)
	do
		sleep 15
		echo 'Waiting for MySql...'
	done
	echo 'MySql ready!'

# LUMEN MIGRATIONS -----------------------------------

	if [ "${MIGRATION_RUN}" == 'execute' ] ; then
		echo 'Running Migrations...'
		cd /var/www/html
		php artisan migrate
		if [ $? -eq 0 ]; then
			cd /var/www/html
			echo 'Migrations done!'
		else
			echo 'Migrations fail!'
			exit 1
		fi
		if [ "${ENVIRONMENT_MODE}" == 'Production' ] ; then
			echo 'No more tasks. Not running Apache. Exiting...'
			exit 0
		fi
	fi


# RUN -----------------------------------


	echo 'Starting Apache Web Server...'
	# first arg is `-f` or `--some-option`
	if [ "${1#-}" != "$1" ]; then
		set -- apache2-foreground "$@"
	fi
		
	exec "$@"



